services:
    frontend:
        container_name: swt_frontend
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        ports:
          - "3000:3000"
        restart: always
    backend:
        container_name: swt_backend
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        ports:
          - "3001:3001"
        restart: always
    backend-external:
        container_name: swt_backend_external
        build:
            context: ./backend-external
            dockerfile: ./Dockerfile
        ports:
          - "3002:3002"
        restart: always
    database:
        container_name: swt_db
        image: mysql:9.3.0
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "test"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
        ports:
            - "3306:3306"
        volumes:
            - ./database:/docker-entrypoint-initdb.d
        restart: always
